# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

COPY ./src/eShopLite.StoreInfo /source/eShopLite.StoreInfo
COPY ./src/eShopLite.DataEntities /source/eShopLite.DataEntities

WORKDIR /source/eShopLite.StoreInfo

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final

WORKDIR /app

COPY --from=build /app .

USER $APP_UID

ENTRYPOINT ["dotnet", "eShopLite.StoreInfo.dll"]
