# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

COPY ./src/eShopLite.Store /source/eShopLite.Store

WORKDIR /source/eShopLite.Store

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final

WORKDIR /app

COPY --from=build /app .

RUN chown $APP_UID /app

USER $APP_UID

RUN touch /app/Database.db

ENTRYPOINT ["dotnet", "eShopLite.Store.dll"]
