# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

COPY ./src/eShopLite.Products /source/eShopLite.Products
COPY ./src/eShopLite.DataEntities /source/eShopLite.DataEntities

WORKDIR /source/eShopLite.Products

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final

WORKDIR /app

COPY --from=build /app .

RUN chown $APP_UID /app

USER $APP_UID

RUN touch /app/Products.db

ENTRYPOINT ["dotnet", "eShopLite.Products.dll"]
